version: "3.9"

services:
  auth-service:
    build: .
    container_name: auth_service
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auth_db
      - JWT_SECRET_KEY=supersecret
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
